### PR TITLE
use withPlugin api, fix build with dolphin studio

### PR DESCRIPTION
**Pull request by digitalbuddha**
Not sure if the alpha is ok, I was using android studio dolphin and could not sync. Happy to revert and use older Studio

### CODE REVIEW

**Review by rharter — APPROVED** [review]
Looks grea, thanks!

**Comment by rharter** [comment]
Just need to sign the CLA and I can merge this.

**Comment by digitalbuddha** [comment]
Seems like smth wrong with my git user I can check this tonight/in am

**Comment by rharter** [comment]
This might be a git config issue. Maybe you need to run `git config --global user.email "..."`, or do that with a different email?

[Deets](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#_your_identity)

**Comment by rharter** [comment]
Fixes #10

**Pull request merged**
